openapi: 3.0.0
info:
  title: Graph Traversal API
  version: 1.0.0
  description: API for performing graph traversal operations.

paths:
  /traverse:
    post:
      summary: Perform graph traversal
      description: >
        This endpoint performs a graph traversal based on the provided algorithm,
        heuristic (if applicable), start and end points, and the map.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - algorithm
                - startPoints
                - endPoints
                - map
              properties:
                algorithm:
                  type: string
                  description: Name of the graph traversal algorithm.
                  example: "Breadth-First Search"
                heuristic:
                  type: string
                  description: Optional name of the heuristic used for traversal.
                  example: "Manhattan Distance"
                  nullable: true
                startPoints:
                  type: array
                  items:
                    type: integer
                  minItems: 2
                  maxItems: 2
                  description: List of integers representing the start points.
                  example: [1, 2]
                endPoints:
                  type: array
                  items:
                    type: integer
                  minItems: 2
                  maxItems: 2
                  description: List of integers representing the end points.
                  example: [3, 4]
                map:
                  type: array
                  items:
                    type: object
                    required:
                      - node
                      - weight
                    properties:
                      node:
                        type: array
                        items:
                          type: integer
                        minItems: 2
                        maxItems: 2
                        description: List of two integers representing the node.
                        example: [1, 2]
                      weight:
                        type: integer
                        description: Weight of the edge. If the weight is set to -1 then the node is not possible to move through.
                  description: List of tuples representing the graph map.
                  example:
                    [
                      { "node": [1, 2], "weight": 4 },
                      { "node": [2, 3], "weight": 5 },
                    ]
      responses:
        "200":
          description: Successful traversal of the graph.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Traversal completed successfully."
                  path:
                    type: array
                    items:
                      type: array
                      items:
                        type: integer
                      minItems: 2
                      maxItems: 2
                    example: [[1, 2], [2, 3]]
                    description: The path traversed as a list of node identifiers.
                  nodeOrder:
                    type: array
                    items:
                      type: array
                      items:
                        type: integer
                      minItems: 2
                      maxItems: 2
                    description: The order of nodes traversed as a list of node pairs.
                    example: [[1, 2], [2, 3]]
        "400":
          description: Bad request - invalid input.
        "500":
          description: Internal server error.
  /graph-traversal-methods:
    get:
      summary: Fetch all legal graph traversal methods
      description: >
        This endpoint retrieves all legal graph traversal methods that this service provides.
      responses:
        "200":
          description: Successfully retrieved the list of graph traversal methods.
          content:
            application/json:
              schema:
                type: object
                properties:
                  methods:
                    type: array
                    items:
                      type: string
                    description: A list of available graph traversal methods.
                    example:
                      [
                        "Breadth-First Search",
                        "Depth-First Search",
                        "A* Search",
                      ]
        "500":
          description: Internal server error.

  /graph-heuristics-methods:
    post:
      summary: Fetch all legal graph traversal methods
      description: >
        This endpoint retrieves all legal graph traversal methods that this service provides.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - method
              properties:
                method:
                  type: string
                  description: Optional name of the heuristic used for traversal.
                  example: "A star"
      responses:
        "200":
          description: Successfully retrieved the list of graph traversal methods.
          content:
            application/json:
              schema:
                type: object
                properties:
                  heuristics:
                    type: array
                    items:
                      type: string
                    description: A list of available graph traversal methods.
                    example: ["Manhattan Distance", Euclidean Distance]
        "500":
          description: Internal server error.
