name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on:
      labels: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Run Docker Container
        run: |
          docker compose down || true
          docker compose build
          docker compose up -d
